### ISSUE TITLE
Ability to access pubkey data directly?

### ISSUE THREAD

**Issue by Fonta1n3** [blockchain/libwally-swift#26]
I would like to display the hex of derived pubkeys to the user so that they may verify the derived pubkeys are what they expect them to be when for example importing a seed (along with the address and wif). When I try and access the raw data of the pubkey like so:

`key.pubKey.data`

 I get an error:

`'data' is inaccessible due to 'internal' protection level`

Is there a way I can disable the internal protection level so that I may access the data directly?

**Comment by Sjors** [comment]
I'm fine with making all these public:
https://github.com/blockchain/libwally-swift/blob/master/LibWally/Address.swift#L260-L262

**Comment by Fonta1n3** [comment]
Thank you for pointing out the file, I was looking in the wrong place :)

**Comment by Sjors** [comment]
There's a PR for it: #27

**Comment by Sjors** [comment]
Done. Private keys are exposed as well, but be careful with that, as I mentioned in #20
