### ISSUE TITLE
P2SH-Segwit and Legacy Single Signature signing occasionally failing

### ISSUE THREAD

**Issue by Fonta1n3** [blockchain/libwally-swift#28]
I am using LibWally-Swift to sign for multisig and single signature transactions/psbt's.

Frequently I get an error for P2SH-Segwit transactions when broadcasting them:

`non-mandatory-script-verify-flag (signature must be zero for failed check(multi)sig operation`

And occasionally for Legacy I get an error when broadcasting as well:

`mandatory-script-verify-flag-failed (operation not valid with the current stack size) (code 16)`

In the readme it states `Compose and sign (SegWit) transaction`. Does that imply non segwit transactions do not have signing functionality? I am confused because in the tests it has examples for signing all three types of transactions.

As a side note if it is a multisig transaction all three formats work fine as do single sig Native Segwit transactions.

Of course I may be doing something wrong... However if you have any obvious advice for me it would be much appreciated. Again thank you for the wonderful library.

**Comment by Sjors** [comment]
You should be able to sign all input types; I removed the confusing "(SegWit)" from the README.

To clarify, you're spending from P2SH-Segwit or from Legacy addresses when you see these errors?

Also to clarify, are you seeing this when signing a PSBT or when signing a Transaction you composed yourself? These are separate code paths.

Do you see it consistently for the same transactions or does it work when you try again?

Examples would be very useful, but don't doxx your mainnet coins...

**Comment by Fonta1n3** [comment]
This was user error. I am using bitcoin core to build the psbt's and was not specifying the `change_type` in the `walletcreatfundedpsbt` arguments and forgot that the node would create segwit wrapped change addresses by default, I was attempting to sign specifically for P2WSH inputs. Works like a charm now that I account for multiple address formats for the inputs.

**Comment by Sjors** [comment]
Thanks for the update. I would still like the library to catch this earlier...
