### ISSUE TITLE
`PSBT.sign(privKey)` seems to only work on multisig transactions

### ISSUE THREAD

**Issue by Fonta1n3** [blockchain/libwally-swift#30]
I may be doing it wrong but I am using the `PSBT.sign(privKey)` function for multi-sig transactions and it works every time. However for single sig transactions I have to fall back to the the traditional way of signing raw transactions. I would very much like to enable users to be able to scan *any* PSBT and have the app sign it if it can.

Just curious if this is by design or if I am doing something wrong here?

EDIT: To clarify when I say it does not work what I mean is the PSBT will never be `finalized` or `complete`, it may actually be signing but the finalization/completion never returns true. I have confirmed with certainty the private key I am trying to use to sign is the correct private key and that there is only one input to sign.

**Comment by Sjors** [comment]
I haven't tried to use PSBT with a single signature, so this could very well be a bug. First step would to add a test case.

**Comment by Sjors** [comment]
See #31 for a demonstration of the problem, thanks @Fonta1n3

**Comment by Fonta1n3** [comment]
Interestingly when I sign the PSBT with an xprv (HDKey) it works for all types of transaction types. Its also much easier way of going about it programmatically.

**Comment by Fonta1n3** [comment]
I can confirm this is not happening anymore.
