### ISSUE TITLE
Error: Can't exec "aclocal" in "Build libwally-core for device and simulator and combine into a single library..." step

### ISSUE THREAD

**Issue by amfathi** [blockchain/libwally-swift#47]
## What I'm trying to do
I'm trying to use `libwally-swift` in my swift project using __cocoapods__ and I'm facing an issue.

## What else I tried to do
So I tried to clone and build `libwally-swift` separately and still facing same error.

### When I run this command
`$ ./build-libwally.sh -dsc`

### I get this error

```
Build libwally-core for device and simulator and combine into a single library...
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
sed: ./tools/build-aux/ltmain.sh: No such file or directory
sed: ./tools/build-aux/ltmain.sh: No such file or directory
sed: ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
sed: ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
```

---

# Useful debugging info:

#### I've followed the installation guidelines
I ran the below commands successfully
```
$ brew install gnu-sed
$ git clone https://github.com/blockchain/libwally-swift.git --recurse-submodules
```

---

* I checked this file `/usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm` and it exists.
* I made sure that my user is the owner and have exec permission to everything inside `/usr/local/Cellar/autoconf/`

* I checked line __326__ that have the issue and here is the containing function

<img width="724" alt="Screenshot 2020-12-27 at 6 45 48 PM" src="https://user-images.githubusercontent.com/22002954/103176646-c6485480-4873-11eb-8579-63f22e0f3fe1.png">

---

**Comment by amfathi** [comment]
@Sjors

**Comment by Sjors** [comment]
Did you try `brew install automake libtool pkg-config` ?

**Comment by amfathi** [comment]
`brew install automake libtool pkg-config` fixed it for me. Thanks!
